name: Build and Test

on:
  push:
    branches-ignore:
      - main # Ignoriere main, um eine mögliche endlose Build-Schleife zu verhindern

jobs:
  build_and_test:
    name: Build and Test Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

    - name: Test
      run: dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build

  push_to_main:
    name: Push to Main Job
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "ubo3694@students.fhv.at"
        git config --global user.name "Ugurcan Borihan"

    - name: Push to main
      run: |
        git checkout main
        git merge --no-ff origin/feature/my-new-feature # Merge feature/my-new-feature into main
        git push origin main
