name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

    # Führen Sie die Unit-Tests mit dem dotnet test-Befehl aus.
    - name: Test
      run: |
        dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build
        if [ $? -eq 0 ]; then
          echo "Unit tests passed. Proceeding with the push to main..."
          git config --global user.email "ubo3694@students.fhv.at"
          git config --global user.name "ubo3694"
          git add .
          git commit -m "Unit tests passed"
          git push origin main
        else
          echo "Unit tests failed. Changes won't be pushed."
        fi
