name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

    - name: Test
      run: dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build

  push_to_main:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Push to main
      run: |
        git checkout main
        git merge --no-ff ${{ github.sha }}
        git push origin main
