name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

      - name: Build
        run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

      - name: Test
        run: dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build

      - name: Push to main if tests pass
        if: success()  # Dieser Schritt wird nur ausgeführt, wenn die vorherigen Schritte erfolgreich waren
        run: git push origin main
