name: .NET Core CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Hier können Sie die gewünschte .NET-Version einstellen.

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

    # Führen Sie die Unit-Tests mit dem dotnet test-Befehl aus.
    - name: Test
      run: dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build

    # Führen Sie den Push-Befehl nur aus, wenn die Tests erfolgreich sind.
    - name: Push to Main Branch
      if: ${{ success() }}
      run: |
        git add .
        git commit -m "CI: Unit tests passed"
        git push
