name: .NET Core CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' # Hier können Sie die gewünschte .NET-Version einstellen.

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore

    # Führen Sie die Unit-Tests mit dem dotnet test-Befehl aus.
    - name: Test
      run: dotnet test TrainingLogbuch/TrainingLogbuch.sln --no-build

    # Fügen Sie hier einen Schritt hinzu, um zu überprüfen, ob die Tests erfolgreich waren, z.B.:
    - name: Check Test Results
      run: |
        if [ $? -eq 0 ]; then
          echo "Unit tests passed. Proceeding with the push..."
        else
          echo "Unit tests failed. Aborting the push."
          exit 1
        fi

    # Führen Sie das Pushen nur aus, wenn die Tests erfolgreich waren.
    - name: Push to Main
      if: success()
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "CI: Unit tests passed"
        git push
