name: StyleCop Check on Main

on:
  push:
    branches:
      - main

jobs:
  stylecop_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Aktualisieren Sie die Version hier

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3 # und hier
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

#    - name: Build Solution
#       run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --configuration Release --warnaserror
      
    - name: Build Solution
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln
