name: StyleCop Analysis

on:
  push:
    branches:
      - main

jobs:
  stylecop_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TrainingLogbuch/TrainingLogbuch.sln

    - name: Build and Analyze (StyleCop)
      run: dotnet build TrainingLogbuch/TrainingLogbuch.sln --no-restore --configuration Release -p:StyleCopTreatErrorsAsWarnings=false

  push_to_main:
    runs-on: ubuntu-latest
    needs: stylecop_check
    if: success()

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Push to main
      run: |
        git checkout main
        git merge --no-ff ${{ github.sha }}
        git push origin main
